# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ECODownloader
                                 A QGIS plugin
 This tool facilitates the acquisition of data available at MSWEP (Beck et al. 2017). 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-24
        copyright            : (C) 2019 by ECOTECNOLOGIAS
        email                : ecoplugin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ECODownloader class from file ECODownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ecodownloader import ECODownloader
    return ECODownloader(iface)
