# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ECODownloader
                                 A QGIS plugin
 This tool facilitates the acquisition of data available at MSWEP (Beck et al. 2017). 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2019 by ECOTECNOLOGIAS
        email                : ecoplugin@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, pyqtSlot
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QFileDialog, QMessageBox, QProgressBar
from qgis.gui import QgsMessageBar
from qgis.core import QgsVectorLayer, QgsProject
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ecodownloader_dialog import ECODownloaderDialog
import os.path
import os
import shutil


class ECODownloader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ECODownloader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ECO-Downloder3.0')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        #self.first_start = None
        
        # ---------------------------------------------------------------------
        
        self.dlg = ECODownloaderDialog()
        
        #----------------------------------------------------------------------

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ECODownloader', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ecodownloader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'ECO-Downloader3.0'),
            callback=self.initialize,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True       
        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ECO-Downloder3.0'),
                action)
            self.iface.removeToolBarIcon(action)

    #--------------------------------------------------------------------------
    def selectOutputDir(self):
            dirname = QFileDialog.getExistingDirectory(None, "Open a folder", "C://")
            self.dlg.lineEditDir.setText(dirname)
            
    def close(self):
        self.dlg.close()        
       
    def insertStates(self):
            index = self.dlg.comboBoxStates.currentIndex()
            pluginpath = os.path.dirname(os.path.realpath(__file__))
            canvas = iface.mapCanvas()
                                       
            if index == 1:
                #polygon = QgsVectorLayer(pluginpath + "\polygons\AC_eco.shp", "AC_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\AC_pontos_eco.shp", "AC_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())  
                
            if index == 2:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\AL_eco.shp", "AL_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\AL_pontos_eco.shp", "AL_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
          
            if index == 3:
                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\AP_eco.shp", "AP_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\AP_pontos_eco.shp", "AP_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 4:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\AM_eco.shp", "AM_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\AM_pontos_eco.shp", "AM_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())

            if index == 5:
                #polygon = QgsVectorLayer(pluginpath + "\polygons\BA_eco.shp", "BA_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\BA_pontos_eco.shp", "BA_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 6:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\CE_eco.shp", "CE_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\CE_pontos_eco.shp", "CE_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())

            if index == 7:
               # polygon = QgsVectorLayer(pluginpath + "\polygons\DF_eco.shp", "DF_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\DF_pontos_eco.shp", "DF_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 8:
#                
               # polygon = QgsVectorLayer(pluginpath + "\polygons\ES_eco.shp", "ES_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\ES_pontos_eco.shp", "ES_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())            

            if index == 9:
               # polygon = QgsVectorLayer(pluginpath + "\polygons\GO_eco.shp", "GO_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\GO_pontos_eco.shp", "GO_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 10:
#                
               # polygon = QgsVectorLayer(pluginpath + "\polygons\MA_eco.shp", "MA_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\MA_pontos_eco.shp", "MA_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 11:

               # polygon = QgsVectorLayer(pluginpath + "\polygons\MT_eco.shp", "MT_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\MT_pontos_eco.shp", "MT_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 12:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\MS_eco.shp", "MS_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\MS_pontos_eco.shp", "MS_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 13:

                #polygon = QgsVectorLayer(pluginpath + "\polygons\MG_eco.shp", "MG_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\MG_pontos_eco.shp", "MG_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 14:
#                
               # polygon = QgsVectorLayer(pluginpath + "\polygons\PA_eco.shp", "PA_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\PA_pontos_eco.shp", "PA_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 15:

                #polygon = QgsVectorLayer(pluginpath + "\polygons\PB_eco.shp", "PB_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\PB_pontos_eco.shp", "PB_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 16:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\PR_eco.shp", "PR_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\PR_pontos_eco.shp", "PR_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 17:

               # polygon = QgsVectorLayer(pluginpath + "\polygons\PE_eco.shp", "PE_eco", "ogr")
                #QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\PE_pontos_eco.shp", "PE_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 18:
#                
                #polygon = QgsVectorLayer(pluginpath + "\polygons\PI_eco.shp", "PI_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\PI_pontos_eco.shp", "PI_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)        
                canvas.setExtent(points.extent())

            if index == 19:

               # polygon = QgsVectorLayer(pluginpath + "\polygons\RJ_eco.shp", "RJ_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\RJ_pontos_eco.shp", "RJ_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
                
            if index == 20:
#                
               # polygon = QgsVectorLayer(pluginpath + "\polygons\RN_eco.shp", "RN_eco", "ogr")
              #  QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\RN_pontos_eco.shp", "RN_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
            if index == 21:

               # polygon = QgsVectorLayer(pluginpath + "\polygons\RS_eco.shp", "RS_eco", "ogr")
              #  QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\RS_pontos_eco.shp", "RS_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())                
            if index == 22:
#                
               # polygon = QgsVectorLayer(pluginpath + "\polygons\RO_eco.shp", "RO_eco", "ogr")
               # QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\RO_pontos_eco.shp", "RO_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
            if index == 23:

               # polygon = QgsVectorLayer(pluginpath + "\polygons\RR_eco.shp", "RR_eco", "ogr")
              #  QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\RR_pontos_eco.shp", "RR_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())                
            if index == 24:
#                
              #  polygon = QgsVectorLayer(pluginpath + "\polygons\SC_eco.shp", "SC_eco", "ogr")
             #   QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\SC_pontos_eco.shp", "SC_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
            if index == 25:

              #  polygon = QgsVectorLayer(pluginpath + "\polygons\SP_eco.shp", "SP_eco", "ogr")
              #  QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\SP_pontos_eco.shp", "SP_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())                
            if index == 26:
#                
              #  polygon = QgsVectorLayer(pluginpath + "\polygons\SE_eco.shp", "SE_eco", "ogr")
             #   QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\SE_pontos_eco.shp", "SE_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())
            if index == 27:
#                
              #  polygon = QgsVectorLayer(pluginpath + "\polygons\TO_eco.shp", "TO_eco", "ogr")
              #  QgsProject.instance().addMapLayer(polygon)
                points = QgsVectorLayer(pluginpath + "\points\TO_pontos_eco.shp", "TO_pontos_eco", "ogr")
                QgsProject.instance().addMapLayer(points)               
                canvas.setExtent(points.extent())                            


            
            
    #Função de abertura da janela do plugin
    def initialize(self):
        
        #Abre o Python Console quando inicia o plugin
        #self.iface.actionShowPythonDialog().trigger()
        self.dlg.progressBar.setValue(0)
        self.dlg.textEditRes.clear()
        
        self.dlg.lineEditDir.clear()
        self.dlg.pushButtonDir.clicked.connect(self.selectOutputDir)
                
        #Limpa a comboBox para não repetir a lista
        self.dlg.comboBoxStates.clear()
        
        #Inserção das opções de download na comboBox
        listStates = [" ", "Acre (AC)", "Alagoas (AL)", u"Amapá (AP)", 
                      "Amazonas (AM)", "Bahia (BA)", u"Ceará (CE)", 
                      "Distrito Federal (DF)", u"Espírito Santo (ES)", 
                      u"Goiás (GO)", u"Maranhão (MA)", "Mato Grosso (MT)",
                      "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", 
                      u"Pará (PA)", u"Paraíba (PB)", u"Paraná (PR)", 
                      "Pernambuco (PE)", u"Piauí (PI)", "Rio de Janeiro (RJ)", 
                      "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", 
                      u"Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", 
                      u"São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)"]
        self.dlg.comboBoxStates.addItems(listStates)
        
        #self.removeLayer()
        self.dlg.show()
        
        self.dlg.comboBoxStates.currentIndexChanged.connect(self.insertStates)    
        
        self.dlg.pushButtonDown.clicked.connect(self.run)
        self.dlg.pushButtonCancel.clicked.connect(self.close)
               
        #----------------------------------------------------------------------

    def run(self):
        """Run method that performs all the real work"""
        
        # TROCAR PARA O DIRETORIO DO SERVIDOR OU PARA O DO SEU COMPUTADOR
        if self.dlg.radioButton3h.isChecked():
            #ALTERAR PARA DIRETORIO CERTO
            filesDir = r"C:\Users\robso\Dropbox\Ecosoft\ECODownloader3.0\stationsFiles\3hr"
        if self.dlg.radioButtonDia.isChecked():
            filesDir = r"C:\Users\robso\Dropbox\Ecosoft\ECODownloader3.0\stationsFiles\diario"
        if self.dlg.radioButtonMen.isChecked():
            filesDir = r"C:\Users\robso\Dropbox\Ecosoft\ECODownloader3.0\stationsFiles\mensal"
        if self.dlg.radioButtonAnu.isChecked(): 
            filesDir = r"C:\Users\robso\Dropbox\Ecosoft\ECODownloader3.0\stationsFiles\anual"
        
        # diretorio de download
        downDir = self.dlg.lineEditDir.text()
        if downDir == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Por favor, selecione diretório.")
            msg.exec_()
            return
            
        
        # lógica para pegar as features selecionadas              
        layer = self.iface.activeLayer()
        selected_features = layer.selectedFeatures()        
        ID = []               
        for f in selected_features:
            line = '%d' % (f['ID']) #%i
            ID.append(line)
                      
        if len(ID) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Por favor, selecione estações.")
            msg.exec_()
            return
            
        self.dlg.progressBar.setMaximum(len(ID))
        count = 0
        for u in ID: 
            for root, dirs, files in os.walk(filesDir): 
                for file in files:                      
                    if file.startswith(u): 
                        fh = open(downDir + "\\" + file, "w+")
                        shutil.copyfile(filesDir + "\\" + file, downDir + "\\" + file)  
                        count += 1
                        self.dlg.progressBar.setValue(count)
                        self.dlg.textEditRes.append(str(u) + " download completado " + "(" + str(count) + "/" + str(len(ID)) + ")")
                        fh.close()
                        
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Download Complete")
        msg.exec_()
        
        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
